version: '3.1'

services:

  backend:
    image: "backend"
    ports:
      - "5000:8080"
    depends_on:
      - "db"
    environment:
        PORT: 8080
        CLOUD_SQL_USERNAME: playuser
        CLOUD_SQL_PASSWORD: 123456
        CLOUD_SQL_DATABASE_NAME: playlist
        DB_LOCAL_HOST: db

  frontend:
    image: "frontend"
    ports:
      - "3000:8080"
        
  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: playuser
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: playlist
    ports:
      - 3306:3306
    volumes:
        - ./playlist-infra/Playlist.sql:/data/application/init.sql
