# Nombre del Workflow
name: Backend Pipeline

# Evento que activa la pipeline en nuestro repositorio
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download do Repositório
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        
      - name: Setup Python
        uses: actions/setup-python@v2 # https://github.com/actions/setup-python
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: |
          cd backend/
          pip install flask flask-wtf

      - name: Docker Login
        uses: docker/login-action@v1 # https://github.com/docker/login-action
        with:
          echo '${{ secrets.¿ }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin '${{ vars.GOOGLE_ARTIFACT }}'

      - name: Build & Push Image
        run: |
          cd backend/
          docker build -t ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}:latest .
          docker push ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}:latest

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Auth GCP
        uses: google-github-actions/setup-gcloud@master # https://github.com/google-github-actions/setup-gcloud
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: Cloud Run Deploy
        run: |
          gcloud run deploy my-backend-app \
            --quiet \
            --region us-central1 \
            --image my-docker-repo/backend:latest \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GOOGLE_PROJECT_ID }} \
            --format json